In [2]:
from langchain_community.document_loaders import TextLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain_community.embeddings import OpenAIEmbeddings
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain.vectorstores import Chroma
from langchain.embeddings import OpenAIEmbeddings
import chromadb

/Users/hossein.glm/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:
from dotenv import load_dotenv
from gitdb.fun import chunk_size

load_dotenv()

True

In [4]:
import pandas as pd
books = pd.read_csv("books_cleaned.csv")

books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [5]:
if "tagged_description" in books.columns:
    print(books["tagged_description"])
else:
    print("The 'tagged_description' column is missing from the DataFrame.")

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: object

In [6]:
books["tagged_description"].to_csv("tagged_description.txt", sep="\n", index=False, header=False)

In [7]:
raw_documents =  TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=0, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1168, which is longer than the specified 0
Created a chunk of size 1214, which is longer than the specified 0
Created a chunk of size 373, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 483, which is longer than the specified 0
Created a chunk of size 482, which is longer than the specified 0
Created a chunk of size 960, which is longer than the specified 0
Created a chunk of size 188, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 296, which is longer than the specified 0
Created a chunk of size 197, which is longer than the specified 0
Created a chunk of size 881, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 1189, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 211, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 513, which is longer than the specified 0
Created a chunk of size 752, which is longer than the specified 0
Created a chunk of size 388, which is longer than the specified 0
Created a chunk of size 263, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 728, which is longer than the specified 0
Created a chunk of size 721, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 473, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 1267, which is longer than the specified 0
Created a chunk of size 681, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 553, which is longer than the specified 0
Created a chunk of size 521, which is longer than the specified 0
Created a chunk of size 280, which is longer than the specified 0
Created a chunk of size 787, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 177, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 533, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 563, which is longer than the specified 0
Created a chunk of size 385, which is longer than the specified 0
Created a chunk of size 410, which is longer than the specified 0
Created a chunk of size 461, which is longer than the specified 0
Created a chunk of size 595, which is longer than the specified 0
Created a chunk of size 476, which is longer than the specified 0
Created a chunk of size 459, which is longer than the specified 0
Created a chunk of size 257, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 614, which is longer than the specified 0
Created a chunk of size 419, which is longer than the specified 0
Created a chunk of size 887, which is longer than the specified 0
Created a chunk of size 693, which is longer than the specified 0
Created a chunk of size 302, which is longer than the specified 0
Created a chunk of size 217, which is longer than the specified 0
Created a chunk of size 277, which is longer than the specified 0
Created a chunk of size 2010, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 479, which is longer than the specified 0
Created a chunk of size 300, which is longer than the specified 0
Created a chunk of size 520, which is longer than the specified 0
Created a chunk of size 647, which is longer than the specified 0
Created a chunk of size 778, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 686, which is longer than the specified 0
Created a chunk of size 548, which is longer than the specified 0
Created a chunk of size 1225, which is longer than the specified 0
Created a chunk of size 406, which is longer than the specified 0
Created a chunk of size 1184, which is longer than the specified 0
Created a chunk of size 1214, which is longer than the specified 0
Created a chunk of size 1191, which is longer than the specified 0
Created a chunk of size 1057, which is longer than the specified 0
Created a chunk of size 244, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 766, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 417, which is longer than the specified 0
Created a chunk of size 208, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 526, which is longer than the specified 0
Created a chunk of size 521, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 338, which is longer than the specified 0
Created a chunk of size 899, which is longer than the specified 0
Created a chunk of size 1270, which is longer than the specified 0
Created a chunk of size 558, which is longer than the specified 0
Created a chunk of size 1635, which is longer than the specified 0
Created a chunk of size 436, which is longer than the specified 0
Created a chunk of size 249, which is longer than the specified 0
Created a chunk of size 777, which is longer than the specified 0
Created a chunk of size 716, which is longer than the specified 0
Created a chunk of size 514, which is longer than the specified 0
Created a chunk of size 958, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1132, which is longer than the specified 0
Created a chunk of size 168, which is longer than the specified 0
Created a chunk of size 1325, which is longer than the specified 0
Created a chunk of size 851, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 801, which is longer than the specified 0
Created a chunk of size 1119, which is longer than the specified 0
Created a chunk of size 836, which is longer than the specified 0
Created a chunk of size 260, which is longer than the specified 0
Created a chunk of size 235, which is longer than the specified 0
Created a chunk of size 732, which is longer than the specified 0
Created a chunk of size 1195, which is longer than the specified 0
Created a chunk of size 710, which is longer than the specified 0
Created a chunk of size 773, which is longer than the specified 0
Created a chunk of size 278, which is longer than the specified 0
Created a chunk of size 307, which is longer than the specified 0
Created a chunk of size 356, which is longer than the specified 0
Created a chunk of size 766, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 716, which is longer than the specified 0
Created a chunk of size 2012, which is longer than the specified 0
Created a chunk of size 308, which is longer than the specified 0
Created a chunk of size 1286, which is longer than the specified 0
Created a chunk of size 1231, which is longer than the specified 0
Created a chunk of size 729, which is longer than the specified 0
Created a chunk of size 750, which is longer than the specified 0
Created a chunk of size 445, which is longer than the specified 0
Created a chunk of size 1242, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 912, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 844, which is longer than the specified 0
Created a chunk of size 1126, which is longer than the specified 0
Created a chunk of size 1073, which is longer than the specified 0
Created a chunk of size 1318, which is longer than the specified 0
Created a chunk of size 361, which is longer than the specified 0
Created a chunk of size 2834, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 240, which is longer than the specified 0
Created a chunk of size 171, which is longer than the specified 0
Created a chunk of size 204, which is longer than the specified 0
Created a chunk of size 570, which is longer than the specified 0
Created a chunk of size 206, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 1141, which is longer than the specified 0
Created a chunk of size 1004, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 710, which is longer than the specified 0
Created a chunk of size 2510, which is longer than the specified 0
Created a chunk of size 954, which is longer than the specified 0
Created a chunk of size 307, which is longer than the specified 0
Created a chunk of size 351, which is longer than the specified 0
Created a chunk of size 639, which is longer than the specified 0
Created a chunk of size 405, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 793, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 254, which is longer than the specified 0
Created a chunk of size 1422, which is longer than the specified 0
Created a chunk of size 1083, which is longer than the specified 0
Created a chunk of size 1144, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 790, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 1086, which is longer than the specified 0
Created a chunk of size 874, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 806, which is longer than the specified 0
Created a chunk of size 1812, which is longer than the specified 0
Created a chunk of size 1830, which is longer than the specified 0
Created a chunk of size 1064, which is longer than the specified 0
Created a chunk of size 955, which is longer than the specified 0
Created a chunk of size 1180, which is longer than the specified 0
Created a chunk of size 281, which is longer than the specified 0
Created a chunk of size 281, which is longer than the specified 0
Created a chunk of size 286, which is longer than the specified 0
Created a chunk of size 1284, which is longer than the specified 0
Created a chunk of size 1642, which is longer than the specified 0
Created a chunk of size 757, which is longer than the specified 0
Created a chunk of size 1930, which is longer than the specified 0
Created a chunk of size 872, which is longer than the specified 0
Created a chunk of size 2008, which is longer than the specified 0
Created a chunk of size 2285, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 1003, which is longer than the specified 0
Created a chunk of size 577, which is longer than the specified 0
Created a chunk of size 288, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 1142, which is longer than the specified 0
Created a chunk of size 557, which is longer than the specified 0
Created a chunk of size 1143, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 1086, which is longer than the specified 0
Created a chunk of size 1483, which is longer than the specified 0
Created a chunk of size 221, which is longer than the specified 0
Created a chunk of size 1135, which is longer than the specified 0
Created a chunk of size 722, which is longer than the specified 0
Created a chunk of size 668, which is longer than the specified 0
Created a chunk of size 765, which is longer than the specified 0
Created a chunk of size 606, which is longer than the specified 0
Created a chunk of size 570, which is longer than the specified 0
Created a chunk of size 965, which is longer than the specified 0
Created a chunk of size 857, which is longer than the specified 0
Created a chunk of size 1032, which is longer than the specified 0
Created a chunk of size 189, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 495, which is longer than the specified 0
Created a chunk of size 652, which is longer than the specified 0
Created a chunk of size 348, which is longer than the specified 0
Created a chunk of size 733, which is longer than the specified 0
Created a chunk of size 525, which is longer than the specified 0
Created a chunk of size 1015, which is longer than the specified 0
Created a chunk of size 970, which is longer than the specified 0
Created a chunk of size 204, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 544, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 207, which is longer than the specified 0
Created a chunk of size 376, which is longer than the specified 0
Created a chunk of size 931, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 854, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 749, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 324, which is longer than the specified 0
Created a chunk of size 241, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 227, which is longer than the specified 0
Created a chunk of size 704, which is longer than the specified 0
Created a chunk of size 1912, which is longer than the specified 0
Created a chunk of size 395, which is longer than the specified 0
Created a chunk of size 485, which is longer than the specified 0
Created a chunk of size 622, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 556, which is longer than the specified 0
Created a chunk of size 386, which is longer than the specified 0
Created a chunk of size 229, which is longer than the specified 0
Created a chunk of size 425, which is longer than the specified 0
Created a chunk of size 418, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 166, which is longer than the specified 0
Created a chunk of size 624, which is longer than the specified 0
Created a chunk of size 2616, which is longer than the specified 0
Created a chunk of size 1580, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 994, which is longer than the specified 0
Created a chunk of size 847, which is longer than the specified 0
Created a chunk of size 263, which is longer than the specified 0
Created a chunk of size 336, which is longer than the specified 0
Created a chunk of size 1530, which is longer than the specified 0
Created a chunk of size 213, which is longer than the specified 0
Created a chunk of size 291, which is longer than the specified 0
Created a chunk of size 2030, which is longer than the specified 0
Created a chunk of size 396, which is longer than the specified 0
Created a chunk of size 1619, which is longer than the specified 0
Created a chunk of size 698, which is longer than the specified 0
Created a chunk of size 822, which is longer than the specified 0
Created a chunk of size 354, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 1189, which is longer than the specified 0
Created a chunk of size 195, which is longer than the specified 0
Created a chunk of size 508, which is longer than the specified 0
Created a chunk of size 663, which is longer than the specified 0
Created a chunk of size 1282, which is longer than the specified 0
Created a chunk of size 260, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 215, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 1277, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1056, which is longer than the specified 0
Created a chunk of size 378, which is longer than the specified 0
Created a chunk of size 269, which is longer than the specified 0
Created a chunk of size 177, which is longer than the specified 0
Created a chunk of size 225, which is longer than the specified 0
Created a chunk of size 222, which is longer than the specified 0
Created a chunk of size 784, which is longer than the specified 0
Created a chunk of size 969, which is longer than the specified 0
Created a chunk of size 613, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 757, which is longer than the specified 0
Created a chunk of size 289, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 963, which is longer than the specified 0
Created a chunk of size 232, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 786, which is longer than the specified 0
Created a chunk of size 648, which is longer than the specified 0
Created a chunk of size 984, which is longer than the specified 0
Created a chunk of size 799, which is longer than the specified 0
Created a chunk of size 193, which is longer than the specified 0
Created a chunk of size 1163, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 203, which is longer than the specified 0
Created a chunk of size 1058, which is longer than the specified 0

In [8]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

In [10]:
import os
# Set OpenAI API key
os.environ["OPENAI_API_KEY"] = ""

# Initialize OpenAIEmbeddings
embedding = OpenAIEmbeddings()

In [11]:
from langchain.vectorstores import Chroma
from langchain.embeddings import OpenAIEmbeddings
from langchain.schema import Document
import chromadb

# Ensure ChromaDB settings are correctly configured
chroma_client = chromadb.PersistentClient(path="./chroma_db")  # Store DB in a directory

db_books = Chroma(
    client=chroma_client,
    #collection_name="test_collection",
    embedding_function=embedding
)

# Add documents to the database
db_books.add_documents(documents)

/var/folders/db/jvp5cdcs4w74f6zvpcfm0rn40000gn/T/ipykernel_85028/3034837995.py:9: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-chroma package and should be used instead. To use it run `pip install -U :class:`~langchain-chroma` and import as `from :class:`~langchain_chroma import Chroma``.
  db_books = Chroma(

['21bb0cd3-cfd2-4e4b-a921-7c283faa1808',
 '2dc31acb-05eb-40aa-bb12-0d0c06001252',
 '07b1a9e7-7131-424a-890b-2ca3f0fa0d4a',
 '0effef18-5c16-41b5-b963-13e3d05bef33',
 '741b9f54-2e72-4f3f-8458-af2fea780267',
 'f740208e-8412-4c4c-9615-e601538de581',
 'a1a135d9-afdf-42d8-8dea-58e2fce61d86',
 'a1a8bb99-5198-406b-bd23-0def26f1377e',
 '0f934f08-c16f-493e-b72d-db39855e13c9',
 '40eb62ee-1f8d-4920-9ac1-cd72fdf30d05',
 '9fc25748-ddec-4de9-951d-a6817bd72837',
 '59e837d9-b503-4faa-b30f-3642c046681d',
 '851bbc86-4e77-45a8-a408-16007339eccb',
 'd45dd1db-1feb-4516-b2d8-b6794ae0aebb',
 'f9655533-9d42-4b8d-9ab9-6c67a00d3977',
 'fd98bdb1-61af-4cc4-9d64-fc99c32fee31',
 '9eee69d0-2353-4699-8d5d-e65d99375988',
 'e605ff80-eb9c-44f6-b2e5-82c5c876e10e',
 '23a6bbd9-4345-41f8-b159-43d71bbb88e2',
 '01196dff-aac8-4e9d-a5fb-2d9ff88bd8ed',
 '9e313910-947d-4a8d-96b0-c98d2303b828',
 '2f73ea04-0c98-4493-8847-de57e2fd8bea',
 '88d2edcd-b3e4-4138-80b4-f38123598fde',
 'd7dc84f2-5daf-478c-a1e4-37f7476aa014',
 'b1874361-c9cb-4827-b433-f5fc206d6780',
 '01ba1050-b922-48d6-854d-17d8fcb047a1',
 '8f70fd4d-4019-480f-b9eb-7b53cf9d9573',
 '841239ac-4fa4-471b-9ecf-d39451227839',
 '85b6eb29-9ebf-4d72-b4db-4e9fa06ed9f0',
 '63892d57-c4b9-46d4-8b22-55749e80d87a',
 '5137fdd8-9a5d-4246-8352-c7e37d2f3a39',
 'b430094e-52fa-452d-b358-c86b887e9087',
 '6e54f0d7-9805-4d21-b8c6-e80643848ed7',
 '3e5e89d0-b7ad-4060-b65b-c05530dda0c1',
 'a3f7bc88-6bd0-4d75-b7db-3f9274aff323',
 '3cb03dc0-9b4a-40ea-9634-1694ad5b15f0',
 'd7e24a75-05a4-41d0-bd27-e854892f5ebc',
 '00f78fda-c593-4e7c-b76d-b694c0a14720',
 '7da65487-3210-4a35-9186-75691e372d8d',
 'd81236de-c7a7-49e7-8a26-ae4066917f01',
 '14f75184-a2ea-43f9-9226-a3d4d82a5a74',
 '964bd15e-d23a-4f0e-9b4c-001d25f36ebd',
 'fcd365c9-0b04-4b7c-b945-e188347fbae3',
 'f3b92cb5-eef4-4fee-9695-8933000a3ef0',
 '24db89be-b388-4f61-bad2-a6aeb3d68dad',
 '0fe8c168-a00a-4cdd-bba6-8e18ac93f858',
 '652855e9-00c5-4587-a243-7db8e435b7dd',
 '90277bc1-356f-46e8-9645-ad9d83c57b51',
 '9698b399-361c-423d-96ff-ecfe3d2a0ab0',
 '4c7515b9-9490-4a34-8992-9e26c1d5833f',
 'b7362834-d6ce-4f3c-a429-908d14f1b920',
 'd7c2e9a8-35d7-40b7-9837-68f408f5a5a9',
 'b87e2361-c82d-43c8-8ab3-fc2f60d5d261',
 '9fb13bc1-28a5-4238-ba4a-7e12c38f2736',
 'eea76d31-0886-463d-827a-480a23b8831b',
 'be16297c-2e04-4994-bf7e-0a1ab1e0935e',
 '0818d9ae-a047-4b84-9c4d-5866bacf6fa2',
 '32d2a513-4ea6-4893-89e8-dad2f87f0b4b',
 '86316b74-dab5-466d-a47f-a02bdb8ae777',
 '392e55ca-778c-40c7-8eb9-1e230c44ac6e',
 'a15765b2-fd49-48a5-8fee-7c4437f60af6',
 '493ca2a3-2b17-4c22-a88b-00bd591c6853',
 '29812b55-a410-4654-89d3-451be73b9893',
 '26143c37-3e3c-42e5-846b-49f7df4608bf',
 'e144bbb5-41c3-424d-b011-13b36a26101c',
 'c820b6b1-43b3-4af9-ad5d-60a981a8cb9d',
 'b29cd33e-472c-4ee8-8066-86621924ff5a',
 'bad69bc7-9cb4-4388-ace7-a2ea191e890f',
 '0f6084b5-5ead-4bbe-be27-fe7cdc7364df',
 '09db38ce-07f0-417b-abf1-7ccebd3417af',
 'f710adbd-8cd2-4200-af31-862604d9d267',
 '5770ba2d-a7ee-4eb3-9533-dc3363b7e56f',
 '65e90a1a-0986-462c-b6b5-5071880c2516',
 '8ffc4921-0748-4593-949c-154a3039e1f6',
 '8aedd489-d5a6-4484-8a0e-ddda480fea4f',
 '1af419ea-5464-41e5-9475-e6d8bc6d56d5',
 '75350398-9fd1-41dd-a5cb-d95c0d66e34f',
 'b0509fd1-137e-4c9e-8441-6b0fc0eead9e',
 'b9d9168e-7df3-4042-afcb-769141f54281',
 'e1ff8ed9-19c1-49d0-96b3-13ce0bb48ebf',
 'ecdfa5ff-a718-4920-80c7-410da1f04884',
 'c0b2e57d-7d09-43a8-b638-84a537b4654f',
 'cf2863c5-92de-45a2-873d-2ce56e5d7115',
 '01e412d5-f49e-44ee-a65f-e47155d8f652',
 '76591d7e-3164-47b4-a35c-c1fef2f7a6c9',
 'd5018813-ccd4-4cb1-9b8b-a2af21280f9c',
 '3a6ac015-48d5-49fd-9e51-c789d29079b8',
 '178ef50d-5c5a-4f84-bc93-a89a4299d1aa',
 'f9d2c6af-8a20-432c-92c3-f5751afa58df',
 '4406e3c6-0f82-4325-a881-09e6920410f5',
 'ef8ef85c-4099-4309-b709-4e8876246b9d',
 '6e0efd28-b793-4f4a-9408-15dea482a4bc',
 '1859fa6a-71a8-419a-b3e5-7334a67e4ba5',
 '6900eec6-d6b7-4edc-b56c-55e10ebc4ddb',
 '3d7c0c62-f23b-4d31-95ed-a38e1a0aa2a3',
 'a1d20b31-3cfb-4bb0-a7c1-c0acbfaa2d13',
 '67285051-c08d-4696-856a-08ea555b70cd',
 '364fe46a-f1e6-4e74-9928-ab2ba06b555a',
 '8e06e901-ea00-47b3-809a-45601c0d35dc',
 'dca102cd-3a0f-423f-b039-ebb9a6e76e78',
 '5c4fe15c-bf23-4238-ae2c-2e4005f17737',
 '47c861b2-cdac-4585-921b-15d4230f9b78',
 '6ac5ea17-919c-4721-b3b8-cb4043e7f470',
 'c7b98e3b-01a2-49bc-b4e1-c8d483417e77',
 '1fcd192d-e0c5-4fd8-9b8a-67a55c22e2f9',
 'e7d48e6f-41c3-4370-9820-8bdd9b178f2e',
 'ec69e945-4023-438a-a73d-e82a08e166f0',
 '3e826146-6a07-4ff5-9147-bff81b4c6c20',
 'd2a0402e-890c-422b-a244-12f341e5e64f',
 '24048f4b-3982-4823-8cd3-870590973606',
 'b5c47281-efbb-4c35-a17f-d89437d49cbb',
 'd61daaf5-c563-43fb-a2b6-6712a7c094bb',
 '6a2cbe21-d2b5-4451-a9a9-0adcccea9316',
 '0b04d1bf-ca80-4ead-9ea9-4d866a5d71ba',
 'fb960ec3-960d-45a0-8909-f38239d12085',
 'f0fa1b90-4d51-4e1c-9373-0703d254a145',
 'f26ea6eb-846f-4179-85f8-f957f7e126d4',
 '00cb2dbb-1f64-485b-8c3c-a7ef5a243b7f',
 'e3a852a5-abc8-48c0-9be3-fe62425d2714',
 '60656ac8-7b6a-4803-a36f-b8d4e3015b9b',
 '2d987a84-26c2-4020-9acb-af1521ad0459',
 '3f0881f0-7f0f-4249-91d1-1262e385ba87',
 '4472f10a-1c86-408b-8ff4-48286fe092cf',
 'd30a51d0-944e-48ab-8a87-6177a78f12b6',
 '50ee29ec-68a6-4a8a-ac8b-9faabbe3ae11',
 '294422fe-e61d-4e50-9d38-cd4bf2912808',
 '0d620c81-3191-47cd-817a-a36dc9e77cbf',
 'f7929606-118a-4408-ae2f-4d96307702ea',
 '54237757-381c-47ee-a814-c64f48854925',
 'a5b7c35c-b8e2-4e15-9ae7-e22c1fd686fe',
 '8af445b7-dd2f-437a-a03c-edee071b5193',
 '20e7728c-2ca6-4092-b890-ec6e60c9e3e5',
 '8b3d13a1-ae3a-4c06-ba18-7b2db51a6bde',
 '60e59387-4cbf-4e87-868a-52ba9df1ce30',
 '3dce7c9c-0d19-4c47-8e0c-c2379b5851e6',
 'eae9a9c2-7332-4949-88b9-8b1566476dd3',
 '75fa3671-508e-49ff-a299-64adf69e9859',
 '4e6aa1aa-b603-47eb-8f1b-fb5d66386265',
 '14fc06d9-afc1-4c51-b3c8-30da4aef894e',
 '27c1ab70-165b-4256-bed6-6a049db106f8',
 '753782cf-a53d-47cb-b61d-cd21b0ab5acc',
 '1e9ca3f6-9909-494d-ad52-d5ab6fecde8a',
 '0f7cc8fa-b0dc-42f1-96eb-6fcbc6c0f4e4',
 '9144274e-057a-4ba7-a039-e1197ec0921f',
 'fa317c03-f511-444e-a38d-4a0d092664cc',
 'd2045dbb-f0b1-4f0e-8d16-43f7c41655f0',
 '13c80e47-4ca2-428a-9bf4-9a3b9d8dfb70',
 '17aeec91-07e3-433c-9725-5a1759e32c13',
 'd5f92198-8c42-4eea-9720-17716e4f064f',
 'cdde2570-6519-4534-918b-f5b578fdfefe',
 '77c79a0c-3f3f-498b-8fa9-5fb7ad8e58f8',
 '7829b730-642f-415f-829a-e7988dc621d8',
 'd694f639-25cb-4a2f-9fe0-b4c0f889f986',
 'd6449dea-2dcc-410d-acaf-d3892e60a8ca',
 'b5479952-d5ed-49e6-97c8-1ac08d8393a1',
 '011c8c1a-74f2-473e-ad1d-2721af4d5007',
 'f668bb72-89c3-4c3b-865c-c99275c08dcc',
 '93f953e1-a813-40da-93c3-6cd2b6743e42',
 '6c5682b8-8b27-49cb-8a88-eab58490da24',
 '182e1a33-7b50-44b4-a664-268c1bb95f99',
 'c65c7950-d750-429f-a100-3efde1f58e8c',
 '96ac0949-fcfe-4c84-b225-89bf950576f2',
 '8a378745-b806-4c1a-8e49-8b6032edc080',
 'dd955e5d-824a-4048-ad6e-2238041d2aa1',
 '6d6e5429-f607-462a-87ea-d5c65e3d913a',
 '0a84d741-5193-48f7-a8c0-4e01a7912dc1',
 '50c18adf-4758-4ce7-a426-69d04cc780fe',
 'ed2cf042-c40e-4b12-b3e9-9edde520a76a',
 '7ebce638-8c11-418a-abd3-101bc63b64b0',
 'f827f9d1-4d16-46be-9467-a91b73c57ddf',
 '31d0b0a0-b9a2-4681-975b-f3603ee06e70',
 '61db429f-bf63-4cb2-a0ae-628fe169b413',
 '0ba367b9-a30a-4981-bb22-3256be7d7913',
 '1d236bd4-705e-4efd-86e1-e2212e61e8a9',
 'c15ba416-8d6e-4592-b4b9-57bb01853aac',
 '683698e1-6111-424f-9941-32a95f1972d4',
 '601e33f6-9dde-447f-bb45-38c0a1a207d6',
 '967685a5-cf35-4718-8a14-9814232d23fa',
 '9f92d4bc-3a6b-476b-a712-42acf0549b29',
 '66e3ef04-1e48-4d19-942a-dd8b38e80063',
 '77f3b544-5def-4055-a12c-22a92e8c6d37',
 '2210b190-21e6-4334-9d2e-eb3fde153e45',
 '5a89780c-a717-4d3f-8388-274fcdcc9e59',
 '3a57d2b9-6511-4baa-abdd-2d22c6563b66',
 '3f7aaeac-a5aa-4ca9-94d1-014a52736e3f',
 '46d21742-036c-4d9e-83b7-267d67f89d4b',
 'cfc11568-cd3a-41f4-b479-0d8d4fe7e428',
 'dbf77bbf-9fb1-4d65-823c-f8179c7fae9f',
 'c947d020-42b8-411e-8be0-cca4da245889',
 'f772b83d-2edb-4d0f-83b3-ce886339d989',
 'c821aef8-4007-44f6-a570-b0d92e956e3e',
 '951b202f-72af-48f4-b453-1e3c5a451599',
 'a8e8dcd1-a486-4035-a020-1d65ae9f48f6',
 'db0340ce-2ce2-4514-abe9-ac7413aa7fae',
 '52ac4461-2a7a-454e-841d-720dcc4fe113',
 '13e08eeb-7eee-4427-8784-7cba3ccab38e',
 'c4fb3a29-ec5b-4bdc-b7e2-593614f0fe99',
 '0c8bf365-d887-47f2-900a-e05de72cd55a',
 '665ea520-f991-4af9-992f-a1e500133135',
 '2441c7d4-7e36-4fad-b498-f9aef928b35a',
 '4ee56db0-c0b2-47e2-8145-aa3391d9e18a',
 'cf9ec417-eb71-49ad-be4c-488484a016a3',
 '2a07fb73-522b-4fe2-b00c-fee0cf81a985',
 'f107d978-eaca-4e11-80c2-98bf93a0af25',
 'afe709f5-4cbc-4217-8729-df13eb7c1c0f',
 '0626d9fd-6553-4f38-92b0-a88a8b66b877',
 '0f339112-7f1a-4d27-a561-fc95b4242c1f',
 '71bc4f5c-2714-4c5e-a518-d1d637b72dc8',
 '651162ec-e863-404b-bfd8-0f887cb4a04e',
 'f147477e-8cf4-45d5-a67d-92d96467f1d8',
 '959a7bab-56f3-4d2e-82f9-8841fbb813ba',
 'cf353c3a-47cb-466c-ba30-adc433b48e12',
 'cdd97943-d22d-45d1-915a-93ef21fe7a84',
 '10cd37eb-53ca-4110-9b7a-3b38b8191fbd',
 '75be3899-eefb-46e6-be0d-b6fef451122e',
 '1cfe6885-9c12-4fe7-adf0-22ed36bf63e0',
 'df46a49f-cfaa-450d-994a-bb4fd336a4db',
 '3fb1af00-253c-4836-9742-aa8645af03aa',
 'f93e8d2b-f150-42a1-85bc-6f8da7a3e318',
 'a7aa2103-3bf6-479a-a617-1bee6d05ad10',
 '77466f42-7e09-4027-a579-82575a62868c',
 '99a8da96-3b6b-4c05-bc09-09627aad52e9',
 '0b6ef765-1f05-47f1-814b-9c22409fb67e',
 'b390e478-360c-4414-b016-472aeb9618a7',
 'ffbeb626-aefa-4fee-aa63-54a267c15cf9',
 'a9b805f4-9062-4c1c-b0a6-8d99f94c936a',
 '361ff043-e4f9-43b4-9c6e-3320f6fe5109',
 '86e0caa4-21cb-4353-82cc-608c5582071b',
 '2d4f48ee-51dd-497e-bfce-b6b0f7cc17c4',
 '966f1bc8-d2e1-40bd-9879-60498378dd5e',
 '0c3e9ac9-118a-4620-90d0-41ce4db5c3c4',
 '4e79197e-e458-460d-a4f3-04b6dfe70d1b',
 '0e398e80-0087-4f0e-84cc-386cb6c6fd8e',
 '96538a87-c852-4616-beb7-c2efb851b736',
 'bddbb4ff-8181-4832-8fbd-91ffaff80dc7',
 '0cba5da4-323c-4604-8f92-db65b2dd7526',
 '93ba2fd7-b829-458d-9999-1da5e3443d6e',
 'e29c0d83-cd7c-4ab4-a675-a42a352a02c1',
 '7bcf4a0d-bd6a-4a33-b4f5-38c3e70b4a95',
 'f45ea8e7-26ae-4a0c-9972-dff44e61a843',
 'f75ec963-8720-4b34-9311-4e2545c45f9d',
 '04ddd3ea-d38a-4ab6-8bb9-dc705d1a7509',
 '46621d3d-90ae-4c89-b136-e740975b6e49',
 'cbd7857a-6e04-4881-aebb-96d4c3975840',
 'eff9050a-fc0e-4bb2-b06c-2a66097dac98',
 'efa04b96-ccc5-4c4c-9998-8cbd9f24e2ba',
 '5c1fc8ef-0ea4-4f11-b7c3-6fda5fb00553',
 '4852959e-b977-4e98-b795-a4fb846a4a51',
 'b686e9f1-aac3-4c02-b341-ed1af3b3d826',
 '1042cbe5-f0b8-4b18-b5a5-218f200f45a1',
 'f438291f-930d-478a-b10f-431dcef3629a',
 'c2549e9b-bba2-4546-b983-4a48737dcfe7',
 '2c482daa-1bb9-427a-b27e-067af105a0a0',
 'e67a8514-d5a1-4c85-8393-5b7aef00fff2',
 '60c5222c-7344-41c4-9446-dac03f636c4d',
 '72dc7152-1df9-4b40-86aa-72b45f859f84',
 '8c0dfb8a-6eac-4db1-9d52-c62a1eebc1dc',
 '1962a636-c770-46fc-89b8-340fe51c0d8d',
 '23fcbdad-ca6f-449b-b395-a974174d96ed',
 '7601dd2f-d33b-44fb-b2dd-9d5ca40036ff',
 'dcf8cc92-fd07-4ef9-b4c6-81260f132f1b',
 'a93d3717-92e9-463d-aafd-750d403d93da',
 '931d037e-b70f-4d08-83a9-cd58bbd90874',
 '0a0ba79a-6efa-45ee-b1c3-51d43985ccb7',
 '9a1fa29e-38f9-47a9-a07c-c777e2f706c8',
 '5f419865-9070-45d9-8c31-48df813bcb48',
 '53d19bca-99d4-46d7-9e0e-e4bc161b0e3a',
 '8909bf2a-9a04-48d6-bc9f-7746315613e2',
 '244d9b43-8941-4d7d-af95-a09e272073f0',
 'a52890d7-765a-42ed-9ae6-7b143fdf6ef3',
 'd2f23424-f186-4297-8299-3ce6760468c4',
 'e4b622a3-ff1d-4adb-8e4a-d063240393c3',
 '43aa69d9-18c4-4e29-afb4-3cce0d348542',
 '1c715928-4eff-4eb7-8985-fdd8c4e3d177',
 'fc9fee06-e01f-400b-bb9d-98244bd9b679',
 '05468020-6c81-46e1-9cf6-c7ccba5ceb41',
 'f655ae98-5109-40bb-abbf-6d6f13f741dd',
 '8631c1eb-15ac-4682-b9b7-0d7cf927b3ea',
 '20cad8d5-dbe9-4da1-a4e0-60cdfd838e72',
 '4f98224c-24a2-4ab1-ada4-25bc4dc396ca',
 '2f904aa0-e5a3-4388-bdbc-d95f1bdf0b88',
 'df8a7901-a63c-4330-a2d1-98bc605915f7',
 'cca347b8-b859-43f6-bbb8-de2e7c00fdf2',
 'c8362573-c24c-4f3e-93c1-6e5473ca719f',
 'efafad30-8274-4b63-a5ec-b26d00d65088',
 'ba71901c-1ff7-426d-a217-9ba72421ecc5',
 '8c8a81ef-79fd-4de0-a01c-cfa293450500',
 'd66974a4-045a-4fa4-9e01-bd885cc87dde',
 '4a498766-b7cc-4252-9c62-d357ee5f4801',
 '33b68f6b-426d-4794-8046-9003ed3160b7',
 '123c1b89-d6d1-45d5-8e1e-fd3c1befd4ef',
 'e3029d23-71d8-456b-b836-b119bea5833f',
 '8771cdbf-b765-4ddd-beb9-ef0b8fde7997',
 '5f0ce9c4-79d2-4710-b67f-49f9158f4fcf',
 '360da53f-710c-4770-9c59-756b1d885164',
 'b258d3ca-5a7b-4449-807e-336d63873e87',
 '9ef95a19-db57-43f6-8d77-0ab6a670dcad',
 '8c216f2f-67b8-4052-bac4-b1db06cc954c',
 'd657b30c-7536-46e6-baa8-cc087f48f99e',
 '3c948b1d-7147-4276-a364-9209cec77316',
 'c8eba55b-0f18-4d2e-b40e-f282605a9347',
 '7bfd28c5-07e5-4d01-87e7-c452b7deaaf1',
 'a9ef8e68-7ad3-43a4-9268-d5004ad15d8c',
 '52bf671b-3c13-4a74-8746-473cba75ecfc',
 'a5c4ce7c-c398-407e-9ebc-8472e2ea45c5',
 '9053e491-5393-4a80-b262-0300318af2c5',
 'f759d2fc-b05e-4ec5-a288-a70c22f5d3f5',
 'd03c0839-4656-4c89-af52-45f5b9bbef11',
 '1563eb91-b921-49e6-b229-fe90e25934d8',
 '4d70e414-0d5b-46e7-99ea-aa60cf0610a8',
 '68a4c4cd-9e17-4988-8c6a-652e18818301',
 '8c6dffc0-f48c-4341-89d6-207b12630e3e',
 '21d37dd9-5eee-4d13-a835-49443f6d78b0',
 '11025372-fe90-409f-8a01-d27c742447a7',
 '8725e0d0-2966-45c7-a32f-f301bf8f5282',
 '82ee801f-8089-4043-8bcf-f46c7eda78fd',
 '458ac533-e424-4616-ac51-585301bd93ca',
 'f188395c-966e-4242-b974-acc14f602160',
 '7a516ee3-3768-4877-825a-3abc5fadba08',
 '443c7614-77b6-4883-8f4a-7f5ce7c07adb',
 '7c60d7c5-e40a-4837-ad30-26e205dbe05c',
 'e648366d-b9b0-4bb4-9663-b6e8fd90ea91',
 'c78553d3-250b-4f5a-b1e4-b7b6523f1123',
 '5c786c3d-877a-45c6-a2e7-abac2baabaf1',
 '99fd15c9-d678-4fec-b840-bd28ccfd1117',
 '979de5d0-8dbf-4531-bcf4-c5d4a9e4ee92',
 'ca24a1a1-f077-47df-968c-33655730f01d',
 '926344d1-43aa-4335-a609-66113121e907',
 'b18c4526-4534-4683-baf2-cc09b52d744b',
 '58970f37-2328-49ef-9cf4-679e33062c44',
 '914863be-5149-42dc-acda-9e794ca15d24',
 'ac7b3cd1-50cc-4312-aa21-fd264cb9adda',
 '4ce5a9a7-0cb9-45eb-b085-75a1c2b006ee',
 'ea20918c-054c-4cde-a1ce-ba43b1f80e2d',
 '533ded1b-7ee0-4a33-b6f6-bc88a5f2e335',
 '727aae37-ea93-48d1-86f9-a54e36e9a8de',
 '15ab9d6b-2a9c-4149-aa5a-fe3edf177069',
 'b5c224be-2e59-48d8-af6e-528d86e067ec',
 '7db07fc8-8656-45ef-9df3-d4de01e2f3c4',
 '8c7d5aa1-89c2-4242-a5c5-c8b076d2151e',
 '1b389dea-4d3c-4ebb-aa6c-551a3a965731',
 '593c5aa6-bf22-4f4d-a378-a298c8eaf209',
 '83764bb8-78c2-4201-b5f4-b7f1033d53f3',
 '5e53272c-f9de-4f9e-8ee8-93c22a718d8b',
 'bb82edd6-85a0-4ec1-8818-30e751f12f7a',
 '0df98434-d7eb-445d-9089-3d60939643a0',
 '1fbb04f1-e029-498c-9c67-291d06c4abb3',
 '01c789b2-6f04-40e9-855c-aec9ad898ebd',
 '43dedb37-1fe6-4e98-8591-b364b69b3617',
 '08e4374b-8b21-48df-b551-e5e04db46b4a',
 'cb80efdf-a3e1-4d14-8e3c-0842fc04db7b',
 '51b25213-7c33-4e11-b8cc-8b2a9c62f70c',
 '247b1ff3-b2dd-4380-a8d1-05c5d9b4d1b2',
 '8b0e59a1-51e8-4f00-a71e-9c95585cbd1b',
 '3eb77f0d-fd66-4dbc-8dd6-8354037e89ba',
 '0794a1e4-bb24-4988-bc2d-c4ddff5a77e2',
 '84aba60a-89e3-4d84-ae9e-58c5339e6bbe',
 'd05b99cf-8b58-485b-a42e-b2035b67f978',
 '763f56d7-b8e3-4bc7-9855-e688a526b744',
 '9dc33666-815d-425e-ac86-6c829e04c857',
 'ca77aa5f-39c1-4155-9e20-197a4554168c',
 'dea0122f-9594-4e89-bd91-2a1b4e023acf',
 '18c6f3c0-10cc-4075-a789-a406902be2e8',
 '0da7a09c-96bd-4fc6-aaaa-a79054b39e81',
 'e237e454-df82-4564-b6b8-3e3823f22c58',
 'b32b2f9a-d386-4d98-b30a-6ad98fa74d75',
 'd8361b68-4564-43e2-8135-f8c514004c09',
 '19c2d446-2a94-4246-9ebc-812b7ad5b6d4',
 '47a3fdab-2fd1-421b-8e90-01170502deb5',
 'f082b1ee-d34b-42df-bfd3-064634bd3959',
 'c7cd4db8-a1e2-4bb3-8b76-dfdf63b4a4b9',
 'bff0832f-a1b9-43c9-8afc-183db4c38f10',
 '3890cb78-1678-49bc-bce3-4c794eab2f60',
 '7c3f011e-816e-40ec-b2dd-097e03343e6b',
 '105cfe25-a8ef-4985-a25f-d5deaaaac4bc',
 '1d7308e5-a560-4440-ac91-a6cb0ed7b87f',
 'decdc077-4ba1-4761-8554-2b9798a7f4b7',
 'b261edd8-fba7-4e9b-8690-768c5b4d5a32',
 '419145cc-cc12-4dfb-86d2-920790eaaac7',
 '9d8d6f52-0857-4417-9c50-c57c2423c160',
 '171aa95a-f3b8-4b9f-8bb5-66c94f3750e8',
 '2b9c7219-82ef-432d-abbe-0f2fe117a084',
 'd8485aee-1734-46ce-823c-c31a4cf4379a',
 '6b4e3ed6-52dd-4bc0-94e0-1b7a4c4536bc',
 'db7e02de-e051-424d-a274-2d4f73992025',
 '8a1074b3-394e-4c04-b64e-1dbc3ffc15e9',
 '70052601-d6b5-4c2e-ace6-cc04b4c0e93e',
 'e52e88d8-9287-46fe-9111-1ad24d301464',
 '56eb4135-fd9e-4dbd-80e3-455f930a5583',
 '37fc6f67-47af-4dc0-b797-42fbe97e20be',
 '86e2f5eb-38ae-4bb3-848d-38691984ac03',
 '63bfea27-ba30-4c5f-a087-d5be85fcd440',
 '6e1b662e-2fac-427a-aa87-4e2d4ddb6dd0',
 '43b08b23-ec93-466a-87ad-5008d4a92c2a',
 '15e1254d-0bc6-461e-8841-13541466f1f2',
 'a8f6d116-9b4e-4489-807f-9e6eeef276aa',
 '1946af32-95d6-48f0-b583-193be737b693',
 'a2c2b079-7500-4223-9bb5-9d5024ee4c52',
 'd0366b9e-8691-4f54-bedb-7c35da02e0e6',
 'a4d6facd-f669-4a5d-8218-6df1c9148df7',
 '6c449c94-53c6-48f4-9474-deb70613b524',
 'def3da84-b50f-403d-832f-815eec0c8974',
 'c8753dd6-c03b-4036-b19d-89b0caf45d40',
 'd1e3b88b-b738-41c7-906b-09d42659582c',
 'ce4ea6b7-c4ca-4f08-8be8-e5f07e3bd6e5',
 '53ce6b71-a8c0-4775-b055-03186327262e',
 '6a941776-a7c2-413a-bc90-4d8c75cf500a',
 '98eac611-67fa-4ad5-8487-6927321e1ae5',
 '25b3c4cf-065a-448d-93a6-03075e292d57',
 '7dd7481e-e84c-475d-83f6-9425599ee731',
 'fd999c53-403d-4d17-9682-8adee445748f',
 '57694d86-6162-4318-844b-787ac090e068',
 '95327806-4cea-4e1a-9276-e9b3b2c7da3a',
 '2b3fc7cd-9a7f-40c7-bae8-703cd6d7a377',
 '97a1109c-67d1-4b13-a339-c8424afbf532',
 '6ff5bdfc-c807-4eed-8954-9558dbc63abe',
 '6e7518c7-1ba3-4f01-91ba-9d7b0e36ba1a',
 '8bb3a3a0-07ca-4f21-a58b-b47f37d8d711',
 'd3bdf6ed-9cfa-4be1-b73f-54f7fde98cf0',
 'a62243c0-5e9a-4046-ab0f-ac692d7c312f',
 'c1a63aa9-7802-45cf-9364-b639fc55ca53',
 '45e1d74f-0ad5-4502-ada7-7f59ffbfa799',
 '6d3c2601-1de1-48f4-8e70-3b39fe42044c',
 'd1686b87-1731-44f0-a752-20bbe646b262',
 '9a48c625-53e6-4720-a1d7-4d6a764b9e2c',
 'aa65b596-356a-4c7f-b497-2844bbe35d09',
 '6c091d13-1b84-4bb5-aaf7-32737f8eaa99',
 'bcb34d54-a6c7-4e22-95be-afbc82dc5c5e',
 '892277d6-d1b2-475a-91de-e072c6c5f174',
 '1f28af50-3897-4d2a-bcd3-628d4c25c06f',
 '85e1be44-f043-41e6-b3db-c7b7d8371890',
 '64f5ebdb-d8ce-48fc-be15-9e8226160dca',
 '3c42964c-efd2-4d33-9f13-80e664c3987c',
 '400c4817-b8f2-499f-8a9d-a29d9db77654',
 'b03c2579-9634-4b93-83b6-2cb685348fbb',
 '78486bed-ed28-4549-b13d-d861f2f5216a',
 'd834db6d-fec1-47d3-b310-0ee4c21da548',
 'fcced5a2-a276-4d59-8a27-e75608c5768a',
 '211f92e9-ebac-4a3d-bec0-c7fccecb0113',
 '758ce332-87b9-43fe-b0b7-cee0792837c0',
 'd95cd514-ed48-492f-97ea-459dbf91187b',
 '5dc7465c-5683-423c-b1f4-cbcb4966b582',
 'd7629343-2506-480b-a6ab-a3dfa913fc8f',
 'f6a319d8-7631-4aa1-bd5d-54ede059f969',
 '2a5beeb7-e6d6-4e0a-823f-e9cd9580c899',
 '98842631-b7eb-40f1-a3be-b59f90407630',
 'c8e1288d-82c1-4c20-bb36-fea562b674b3',
 '52723210-0920-44b6-b387-8a3fa06a47f7',
 '33d6a006-a2f2-40e2-90e7-2aafd3f71f8d',
 '158406ed-3914-42cb-806f-7d6d76b9735c',
 '29c146be-29a7-49aa-a6c6-b3c59c94dcd6',
 '364c8272-be56-4d75-8d75-319c0981caea',
 '3778548d-af89-49dd-84b2-b13556b5e2b3',
 'e5208859-c892-492c-9892-2ee1146ad28c',
 'e95835c0-e83e-4e40-8d49-d73e6c151b50',
 '4d070fc2-4489-411e-9a82-7052de70ca19',
 '32f90f10-4b9f-44d9-85b4-3d8e72d9e76f',
 '5331e2b5-f851-4262-b9d0-957dc68970ce',
 'b9089116-c156-4865-9300-4297d6ec2139',
 '7d8ac3a2-a69a-424c-a104-78402afdd014',
 'ddb9b479-4b32-4ddb-a5ef-edcf1b758078',
 '4e6ad8cc-5e89-4f03-9dfc-d3a1fbf088b6',
 '089f89d8-5a52-47ab-a0be-2abe4586cd81',
 'b95a39a8-8216-4f63-8c3f-8378507342a7',
 '4eae0efc-ce92-4549-9a95-53e3ccf3be45',
 '3a54a312-cca4-4da7-af52-d5097912d0dc',
 '5964e668-1c42-48a1-be5d-8da50505a17e',
 '40caa834-7b39-45ab-87c8-33a79597f136',
 'd692204e-cbbd-4bd0-827e-564f5f72cbbf',
 'a05b5176-be75-486d-8e6e-8e706c48d21f',
 '7ac02cfb-dd22-4418-adf4-9fd9b1542d1b',
 'b29a6dbc-d1c7-4619-8684-1091778cb9da',
 'd5dec458-f7ca-448a-8be7-82184ae8b729',
 '0441c226-89b7-439f-a721-101413752534',
 '1a7c4532-8612-46c8-9360-64ab55a9a270',
 'a4b86278-779b-4e4a-a586-df11b71e753d',
 '9b374065-0e70-45b1-80b0-35955260711d',
 'b33699c6-e8a6-470b-be85-ede65fe75dd9',
 '843c7afb-10f8-46dd-8e56-94fd1af28983',
 'b899aac8-d627-4801-9aba-783e05eeb300',
 'd9703378-7514-439f-8e49-069b415c8206',
 '995470ff-959b-480b-83c7-9ab76e486727',
 '328d9e2a-9fe1-4920-8a6d-39232bef41dc',
 'db6424b4-4e0b-4c1c-80a9-3e027ae923b1',
 '1d0bc843-b343-411c-96d9-1c239f0b19ca',
 'c646915f-b70a-4828-972f-ac2d5ebb0be5',
 '28e80a2f-f6e5-4ef1-b898-b1ac8e3e74aa',

In [12]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k=10)
docs

[Document(metadata={'source': 'tagged_description.txt'}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(metadata={'source': 'tagged_description.txt'}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(metadata={'source': 'tagged_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(metadata={'source': 'tagged_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(metadata={'source': 'tagged_description.txt'}, page_content="9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(metadata={'source': 'tagged_description.txt'}, page_content="9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(metadata={'source': 'tagged_description.txt'}, page_content="9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(metadata={'source': 'tagged_description.txt'}, page_content="9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(metadata={'source': 'tagged_description.txt'}, page_content="9780689861130 Children will love joining in and imitating the animal noises and sounds in this big, bold board book format, illustrated with Sandra Boynton's seriously silly signature animals."),
 Document(metadata={'source': 'tagged_description.txt'}, page_content="9780689861130 Children will love joining in and imitating the animal noises and sounds in this big, bold board book format, illustrated with Sandra Boynton's seriously silly signature animals.")]

In [13]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [14]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [15]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
31,9780007105045,0007105045,Tree and Leaf,John Ronald Reuel Tolkien,Literary Collections,http://books.google.com/books/content?id=aPb_A...,"""The two works 'On fairy-stories' and 'Leaf by...",2001.0,4.09,176.0,2245.0,Tree and Leaf: The Homecoming of Beorhtnoth : ...,"9780007105045 ""The two works 'On fairy-stories..."
429,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,302.0,The Deer in the Wood,9780064434980 Even the youngest child can enjo...
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,The Sense of Wonder,9780067575208 First published more than three ...
707,9780140568196,0140568190,The Giraffe and the Pelly and Me,Roald Dahl;Quentin Blake,Candy,http://books.google.com/books/content?id=J7FdI...,"A Dahl story in which the giraffe, the pelican...",2001.0,3.81,32.0,16265.0,The Giraffe and the Pelly and Me,9780140568196 A Dahl story in which the giraff...
1078,9780241003008,0241003008,The Very Hungry Caterpillar,Eric Carle,Babytime resource,http://books.google.com/books/content?id=DpGEQ...,Eric Carle's children's classic is the story o...,1994.0,4.29,26.0,340101.0,The Very Hungry Caterpillar,9780241003008 Eric Carle's children's classic ...
1639,9780374422080,0374422087,Everything on a Waffle,Polly Horvath,Juvenile Fiction,http://books.google.com/books/content?id=NimVJ...,This Newbery Honor Book tells the story of 11 ...,2004.0,3.71,150.0,9631.0,Everything on a Waffle,9780374422080 This Newbery Honor Book tells th...
2201,9780440362050,0440362059,My Name is Aram,William Saroyan,Fiction,http://books.google.com/books/content?id=2P3XA...,A small boy finds excitement and promise in th...,1966.0,4.15,151.0,975.0,My Name is Aram,9780440362050 A small boy finds excitement and...
2942,9780618711666,061871166X,The Hungry Tide,Amitav Ghosh,Fiction,http://books.google.com/books/content?id=LN16i...,"Presents a novel of life in modern India, chro...",2006.0,3.94,333.0,11220.0,The Hungry Tide,9780618711666 Presents a novel of life in mode...
3201,9780689823824,0689823827,A Child's Garden of Verses,Robert Louis Stevenson,Juvenile Fiction,http://books.google.com/books/content?id=luTZA...,"Here is a delightful look at childhood, writte...",1999.0,4.30,67.0,21780.0,A Child's Garden of Verses,9780689823824 Here is a delightful look at chi...
3214,9780689861130,0689861133,"Moo, Baa, la la La!",Sandra Boynton,Animal sounds,http://books.google.com/books/content?id=Gz40A...,Children will love joining in and imitating th...,2004.0,4.20,14.0,28261.0,"Moo, Baa, la la La!",9780689861130 Children will love joining in an...
3216,9780689863110,068986311X,The Eagle,Cynthia Rylant;Preston McDaniels,Juvenile Fiction,http://books.google.com/books/content?id=cxC9X...,Two mice that live in a lighthouse along with ...,2005.0,4.08,64.0,155.0,The Eagle,9780689863110 Two mice that live in a lighthou...
3442,9780744578263,0744578264,The Sea-thing Child,Russell Hoban,Birds,http://books.google.com/books/content?id=CEt9O...,"Washed up on the beach during a storm, the sea...",2000.0,3.79,48.0,100.0,The Sea-thing Child,9780744578263 Washed up on the beach during a ...
3581,9780763620875,0763620874,Judy Moody Saves the World!,Megan McDonald,Juvenile Fiction,http://books.google.com/books/content?id=xDIRB...,When Judy Moody gets serious about protecting ...,2004.0,4.03,160.0,5883.0,Judy Moody Saves the World!,9780763620875 When Judy Moody gets serious abo...
3582,9780763621643,0763621641,Castle Diary,Richard Platt;Chris Riddell,Juvenile Fiction,http://books.google.com/books/content?id=rFUBA...,As a page in his uncle's castle in thirteenth-...,2003.0,3.84,128.0,1072.0,Castle Diary: The Journal of Tobias Burgess,9780763621643 As a page in his uncle's castle ...
3591,9780764122781,0764122789,Aquatic Turtles,Richard D. Bartlett;Patricia Bartlett,Pets,http://books.google.com/books/content?id=ket2b...,Titles in this series present basic informatio...,2003.0,3.80,46.0,20.0,"Aquatic Turtles: Sliders, Cooters, Painted, an...",9780764122781 Titles in this series present ba...
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...
3748,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,9.0,Baby Einstein: Birds,"9780786808373 Introducing your baby to birds, ..."
3749,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,Baby Einstein: Babies,"9780786808380 Introduce your babies to birds, ..."
3750,9780786808397,078680839X,Baby Einstein: Dogs,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=qut8t...,"Introduce your baby to birds, cats, dogs, and ...",2002.0,3.81,20.0,26.0,Baby Einstein: Dogs,"9780786808397 Introduce your baby to birds, ca..."
3751,9780786808717,0786808713,Baby Einstein: What Does Violet See? Raindrops...,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=95IIA...,A very special puddle sets Violet the mouse of...,2002.0,3.25,18.0,16.0,Baby Einstein: What Does Violet See? Raindrops...,9780786808717 A very special puddle sets Viole...
3760,9780786812912,0786812915,The Big Box,Toni Morrison;Slade Morrison,Juvenile Fiction,http://books.google.com/books/content?id=LyYKA...,"In her first illustrated book for children, th...",2002.0,3.95,48.0,375.0,The Big Box,9780786812912 In her first illustrated book fo...
3764,9780786818723,0786818727,Baby Einstein: Violet's House,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=bC4HA...,"Violet, a very curious young mouse, invites ba...",2003.0,3.98,10.0,39.0,Baby Einstein: Violet's House: A Giant Touch-a...,"9780786818723 Violet, a very curious young mou..."
3765,9780786819119,0786819111,"Baby Einstein: Water, Water Everywhere","Disney Book Group,",Juvenile Fiction,http://books.google.com/books/content?id=tuAdA...,Charming illustrations and playful rhythmic ve...,2003.0,3.70,10.0,77.0,"Baby Einstein: Water, Water Everywhere",9780786819119 Charming illustrations and playf...
3797,9780789458209,0789458209,Tree,David Burnie,Juvenile Nonfiction,http://books.google.com/books/content?id=Qwsqj...,Photographs and text explore the anatomy and l...,2000.0,4.07,64.0,5.0,Tree,9780789458209 Photographs and text explore the...
4264,9780941807555,094180755X,The Little Big Book for God's Children,Lena Tabori;Alice Wong,Religion,http://books.google.com/books/content?id=s2PfT...,THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wo...,2001.0,4.88,352.0,8.0,The Little Big Book for God's Children,9780941807555 THE LITTLE BIG BOOK FOR GOD'S CH...